### PR TITLE
Feat/build composite shapes

### PR DESCRIPTION
**Pull request by aviveiros11**
PR to compose and wrap multiple "Simple Shapes" into "Composite Shapes" via the ShapesWrapper class.  If `type` is not provided it is assigned as a `point` base class for now - with inferred typing coming shortly.  

To Test: 

- Run the NREL VAV Cooling Only jupyter notebook example for Composite Shape construction and confirm validation.

### CODE REVIEW

**Comment by corymosiman12** [comment]
Hey dude - you had the implementation correct, the reason it wasn't validating is because you had two things named exactly identical. I would also recommend just adding the below as methods on the class, which would make it really slick to use. Good job mayne.
image

**Review by corymosiman12 — CHANGES_REQUESTED** [review]
Minor request to add as methods. Else looks good.

**Comment by MatthewSteen** [comment]
@aviveiros11 the notebook worked for me. My only comment is to add tests for the new methods.

**Review by MatthewSteen — COMMENTED** [review]
@aviveiros11 the notebook worked for me. My only comment is to add tests for the new methods if that makes sense with your (better) understanding of the code.

**Pull request merged**
